---
- name: Download stable release of Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  become: true

- name: Change permission on docker-compose
  file:
    path: /usr/local/bin/docker-compose
    state: file
    owner: root
    group: root
    mode: 0755
  become: true
