{
 "title": "Crawler Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WEB-page served",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Application pages parsed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    { "expr": "crawler_pages_parsed", "legendFormat": "Count" }
   ]
  },
  {
   "title": "WEB-page generation time bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "web_page_gen_time_bucket", "legendFormat": "{{ le }}" }
   ]
  },
  {
   "title": "Application site connection time bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_bucket",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Application page parse time bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "crawler_page_parse_time_bucket", "legendFormat": "{{ le }}" }
   ]
  },
  {
   "title": "Logs of UI",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{app=\"crawler\",component=\"ui\"}"
    }
   ]
  },
  {
   "title": "Logs of application",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{app=\"crawler\",component=\"app\"}"
    }
   ]
  }
 ]
}