app:
  replicas: 1
  image: noirgt/crawler-app
  service_port: 8000
  env: {
    MONGO: "mongo",
    MONGO_PORT: "27017",
    RMQ_HOST: "rabbitmq",
    URL: "https://vitkhab.github.io/search_engine_test_site/",
    CHECK_INTERVAL: "60",
    EXCLUDE_URLS: ".*github.com"
    }

ui:
  replicas: 2
  image: noirgt/crawler-ui
  service_port: 8000
  env: {
    MONGO: "mongo",
    MONGO_PORT: "27017"
  }

mongo:
  replicas: 1
  image: mongo:3.2
  service_port: 27017
  volumes: [
    {mongo-persistent-storage: "/data/db"}
  ]

rabbitmq:
  replicas: 1
  image: rabbitmq:3.8.29
  service_port: 5672
